rootLogger: DEBUG, console, file

#
# Put the name of any module -- using its config path -- in the section below.
#
logger:
  # log action execution errors for easier debugging
  action :      DEBUG

  index:
    shard:
      recovery: DEBUG
    store:      INFO
    gateway:    DEBUG
    engine:     DEBUG
    merge:      DEBUG
    translog:   DEBUG
  cluster:
    service:    DEBUG
    action:
      shard:    DEBUG
  gateway:      DEBUG
  discovery:    DEBUG
  jmx:          DEBUG
  httpclient:   INFO
  node:         DEBUG
  plugins:      DEBUG

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ABSOLUTE}][%-5p][%-25c] %m%n"

  file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ABSOLUTE}][%-5p][%-25c] %m%n"
      
