#Wed Mar 27 22:47:41 CET 2013
param.fileFiltered=/user/karma/hadoop/DBLive13-08012013/rsu/dco/schedulestohistorize/130114/OUT/DFLBC/UPDYSDFLBCCHROS/r-00000.avro_FILTERED
pig.script=filter.pig
type=pig
hadoop.cluster=hdfs/cluster/conf_tst-hadoopkarmashaqal-st.france.airfrance.fr
param.fileToFilter=/user/karma/hadoop/DBLive13-08012013/rsu/dco/schedulestohistorize/130114/OUT/DFLBC/UPDYSDFLBCCHROS/r-00000.avro
param.filterValue="fsdf"
param.filterParam=INDIV_SS
