package org.bigloupe.web.service.common;

import java.io.File;
import java.util.Collection;

import javax.servlet.ServletContext;

import org.apache.commons.io.FileUtils;
import org.apache.tools.ant.DirectoryScanner;
import org.atmosphere.cpr.Broadcaster;
import org.atmosphere.cpr.BroadcasterFactory;
import org.bigloupe.web.BigLoupeConfiguration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.web.context.ServletContextAware;

/**
 * Manage log generated by scheduler or pig execution
 * 
 * @author bigloupe
 * 
 */
@Service
public class LogService implements ServletContextAware {
	private ServletContext servletContext;

	@Autowired
	BigLoupeConfiguration configuration;

	@Override
	public void setServletContext(ServletContext servletContext) {
		this.servletContext = servletContext;
	}

	/**
	 * Display log file available in pig or scheduler directory each 5 s
	 */
	@Scheduled(fixedDelay = 5000)
	public void logScanner() {
		if (servletContext != null) {
			String[] includedLogFiles = getListStringLogFile();
			Broadcaster broadcaster = BroadcasterFactory.getDefault().lookup(
					"pig", true);
			StringBuffer stringBuffer = new StringBuffer();
			int i = 0;
			for (String logFile : includedLogFiles) {
				i++;
				if (i == 1)
					stringBuffer.append("<tr>");
				stringBuffer
						.append("<td><a href=\"")
						.append(BigLoupeConfiguration.getConfigurationWebBigLoupeServer() + "/viewFileLog.html?fileLog=").append(logFile);
				stringBuffer.append("&logDir=").append(configuration.isPigLogDirOrSchedulerLogDir()).append("\" target=\"_blank\">").append(logFile).append("</a></td>");
				if (i == 3) {
					stringBuffer.append("</tr>");
					i = 0;
				}
			}
			for (int j = 0; j <= (i % 3); j++)
				stringBuffer.append("<td>&nbsp;</td>");
			broadcaster.broadcast(stringBuffer.toString());
		}

	}

	/**
	 * Retrieve Log files directory to scan
	 */
	private String[] getListStringLogFile() {
		String pathToScan;
		if (configuration.isPigLogDirOrSchedulerLogDir()) {
			pathToScan = servletContext.getRealPath(configuration
					.getPigDirectory());
		} else
			pathToScan = servletContext.getRealPath(BigLoupeConfiguration
					.getSchedulerDirectory());

		DirectoryScanner scanner = new DirectoryScanner();
		scanner.setIncludes(new String[] { "**/*.log" });
		scanner.setBasedir(pathToScan);
		scanner.scan();
		String[] includedLogFiles = scanner.getIncludedFiles();
		return includedLogFiles;
	}

	
	/**
	 * Retrieve Log files directory to scan
	 */
	private Collection<File> getListLogFile() {
		String pathToScan;
		if (configuration.isPigLogDirOrSchedulerLogDir()) {
			pathToScan = servletContext.getRealPath(configuration
					.getPigDirectory());
		} else
			pathToScan = servletContext.getRealPath(BigLoupeConfiguration
					.getSchedulerDirectory());

		return FileUtils.listFiles(new File(pathToScan), new String[] { "log"}, true);
	}
	
	/**
	 * Delete log
	 * @param pigLogDirOrSchedulerLogDir
	 */
	public void deleteLog() {
		Collection<File> includedLogFiles = getListLogFile();
		for (File logFile : includedLogFiles) {
			logFile.delete();
		}
		
	}
}
